travis:
  secure:
    BINSTAR_TOKEN: v1mLoDhBZxI89lACfKXIcPbhZkIxIeNhCmX3hmiW4WLlBPX7sLWfH+8kiHp+xgtxAq9k5gg0zfQWll15usaMG5c/D6ks5JJ/1QCbPMEI7ehrYC7ll6W7dHY/uTmSDQ9nNgSSsZ0q6ASGHtwalwG6zcZy4XEE1l0Nw8PRHDJnJ232/I3yja4RwZsmc+tiupo2CoODP44LzuARYgXUw98lvko8KEBLUtum/WD18NVQ2CjZNWs6SMd1t2tjnFnXJ5YPCq2VqqU9s9DUSzS5uFuBQdul5S4bzpZyrTziilDL5sMp5lh7N4ly6mTw6kjt7d5/G6NecBFDaaSeQFBRStSh3UnYgBOKwROnyWP8PqxTqodnWoroCITyaGa60h7lKjMZ49NBOtkLDUeGfuv2ntn1xLIuf1yzB/Rk1oMdcS0UBaMuSugeNqSpXdXbQPr9YpR4DkCJ4mMtrvSHwp0SNlfVttnmjbSfMQRzQsaKxH1S1pMBBxOG0b7qXNng5FGO71lWQBojO8ha7cdIo7gbwY1FHxTMW6x4wAX7YTXHaVNysyhelHyLCs2XSR6OrA4iezFoxovAEUuO9OisdwAGAtYc0UdvvL/Hu7Dx6hq9fiQp3J/zGphuuZqSJeaRm+CRrB1FqgbPFgAb2Mo3B5ae9PmbBFNZ12dHjZbIMn4R0Bqbw4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
